### ISSUE TITLE
Support creating offline tables for existing views

### ISSUE THREAD

**Issue by laxmanchekka** [hypertrace/view-generator-framework#37]
## Use Case
Pinot recommends to use OFFLINE tables for data with longer retention.

## Proposal
Following approaches to do this

### Remove view-creator-framework
Current view creator framework does the parsing of application configuration and composes pinot table and schema configuration by parsing it. The framework derives the pinot types from Avro bean and auto defines the schema. Though this offers minor advantage, it constrains the usage of new features in Pinot table/schema config (like task config for REALTIME, null value config, default value configs, date time pattern configs, etc. ). We can completely remove this adapter code. And directly use REST apis and json configs (schema & table). This unlocks the full features of Pinot schema/table config.

### Enhance the current framework
Make changes to the current framework to support all the features we need (OFFLINE table creation, task configuration for REALTIME).

**Comment by kotharironak** [comment]
I would suggest going with the first option `Remove view-creator-framework` in long run by maintaining the same schema/table config as JSON as-is. This will have minor overhead on manually adding columns to schema file based on avdl file changes, but would be easy enhance any other properties.
